# Generated by Django 5.2 on 2025-05-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
