# Generated by Django 5.2 on 2025-05-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_number_alter_message_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='profile',
        ),
    ]
