# Generated by Django 5.2 on 2025-05-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_education_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='profile',
        ),
    ]
