# Generated by Django 5.2 on 2025-05-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_experience_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
    ]
